<?php
// 1. Define the path to the PDF you just generated
$pdf_path = 'daily_report.pdf';

// 2. Prepare the data for the Node.js Bridge
$data = [
    'chatId' => '923057629149@c.us', // Use @g.us for a Group ID
    'filePath' => $pdf_path,
    'caption' => "🏥 *Daily Progress Report*\nGenerated by: SANA ULLAH"
];

// 3. Send to the Local Node.js Server (running on port 3000)
$url = "http://localhost:3000/send-pdf";
$options = [
    'http' => [
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ],
];

$context  = stream_context_create($options);
$result = file_get_contents($url, false, $context);

if ($result === FALSE) { 
    echo "Error: Bridge not running."; 
} else {
    echo "Report sent to WhatsApp Group!";
}
?>