<?php 
include 'includes/connect.php'; 
if(isset($_GET['date']))
{
    $date = $_GET['date'];
    $br_id = $_GET['br_id'];
}
elseif(isset($_POST['date']))
{
    $date = $_POST['date'];
    $br_id = $_POST['br_id'];
}
else
{
    exit(0);
}
?>
<html>
<head>
    <title><?php echo get_branch_tag_by($br_id)." ";echo date_format(date_create($date), "m-Y"); ?> MONTHLY PROGRESS REPORT </title>
</head>
<body>
    
<table border = "solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS MONTH <?php echo date_format(date_create($date), " F Y"); ?></h3>
    <h5 align = "center">PROGRESS REPORT IS GENERATED BY: <i><?php echo $user_name; ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>ID</th>
            <th>BRANCH</th>
            <th>NAME</th>
            <th>OPD</th>
            <th>LAB</th>
            <th>LAB%</th>
            <th>USG</th>
            <th>SVD</th>
            <th>D&C</th>
            <th>OPERATION</th>
            <th>DENTAL</th>
            <th>SKIN</th>
            <th>EYE</th>
            <th>ADMISSION</th>
            <th>EMERGENCY</th>
            <th>ECG</th>
            <th>GYNAE TOKEN</th>
            <th>GYNAE</th>
            <th>REF. BY</th>
            <th>REF. TO</th>
            <th>COLLECTION</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $total_lab = 0;
    $total_opd = 0;
    $labs_percentage = 0;
    $total_cash = 0;
    $total_patients = 0;
    $total_refered = 0;
    $total_refered_to = 0;


    $s = 0; 
    $opds = 0;
    $cons_opds = 0;
    $labs = 0;
    $usgs = 0;
    $svds = 0;
    $dncs = 0;
    $procedures = 0;
    $cons_dentals = 0;
    $skins = 0;
    $eyes = 0;
    $admissions = 0;
    $emergrncy = 0;
    $ecg = 0;
    $gynaes = 0;
    $gynae_system = 0;
    $refered = 0;
    $refered_to = 0;
    $total_admissions = 0;
    $total_procedures = 0;
    $total_gynae_system = 0;
    $total_dncs = 0;
    $total_svds = 0;
    $total_skins = 0;
    $total_eyes = 0;
    $total_usg = 0;
    $total_lab = 0;
    $total_medicine = 0;
    $total_opds = 0;
    $total_cons_opds = 0;
    $total_gynaes = 0;
    $total_cons_dentals = 0;
    $total_emergency = 0;
    $total_ecg = 0;
    $select = "SELECT DISTINCT tokans.doctor_id, users.u_name , branchs.tag_name, COUNT(CASE WHEN tokans.tokan_type_id <= 100 THEN tokans.tokan_type_id END) AS opd FROM `tokans` INNER JOIN users ON tokans.doctor_id = users.id INNER JOIN branchs ON users.branch_id = branchs.id WHERE tokans.created like '$date%' AND tokans.branch_id = '$br_id' AND tokans.status = '1' GROUP BY tokans.doctor_id ORDER BY tokans.doctor_id ";
    $run = mysqli_query($con, $select);
    $count_run = mysqli_num_rows($run);
    if(mysqli_num_rows($run) > 0)
    {
        while($row = mysqli_fetch_array($run))
        {
            $opd = $row['opd'];
            $total_opd = $total_opd + $opd;
            $doctor_id = $row['doctor_id'];
        $cash = 0;
        $patients = 0;
        $select_opd = "SELECT SUM(cash) AS total_cash, COUNT(CASE WHEN tokans.tokan_type_id < 100 THEN tokans.id END) AS total_patients FROM `tokans` WHERE tokans.doctor_id = '$doctor_id' AND tokans.branch_id = '$br_id' AND tokans.status = '1' AND tokans.created LIKE '$date%' ";
        $run_opd = mysqli_query($con, $select_opd);
        if(mysqli_num_rows($run_opd))
        {
            while($row_opd = mysqli_fetch_array($run_opd))
            {
                $cash = $row_opd['total_cash'];
                $total_cash = $total_cash + $cash;
                $patients = $row_opd['total_patients'];
                $total_patients = $total_patients + $patients;
            }
        }
        
        $select_data = "SELECT items.category_id, COUNT(items.category_id) AS count_data, COUNT(DISTINCT item_by_doctor.tokan_no) AS count_token FROM `item_by_doctor` INNER JOIN item_register_to_branches ON item_by_doctor.item_id = item_register_to_branches.id INNER JOIN items ON item_register_to_branches.item_id = items.id INNER JOIN tokans ON item_by_doctor.tokan_no = tokans.id  WHERE tokans.created LIKE '$date%' AND item_by_doctor.doctor_id = '$doctor_id' AND item_by_doctor.branch_id = '$br_id' AND items.category_id IN (2, 3, 29, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 44) AND tokans.status = '1' GROUP BY items.category_id ";
        $run_data = mysqli_query($con, $select_data);
        if(mysqli_num_rows($run_data) > 0)
        {
            while($row_data = mysqli_fetch_array($run_data))
            {
                $category_id = $row_data['category_id'];
                $count_data = $row_data['count_data'];
                $count_token = $row_data['count_token'];
                if($category_id == 2)
                {
                    $labs = $count_token;
                    $total_lab = $total_lab + $labs;
                }
                elseif($category_id == 3)
                {
                    $procedures = $count_token;
                    $total_procedures = $total_procedures + $procedures;
                }
                elseif($category_id == 29)
                {
                    $cons_opds = $count_token;
                    $total_cons_opds = $total_cons_opds + $cons_opds;
                }
                elseif($category_id == 31)
                {
                    $cons_dentals = $count_token;
                    $total_cons_dentals = $total_cons_dentals + $cons_dentals;
                }
                elseif($category_id == 32)
                {
                    $cons_skins = $count_token;
                    $total_cons_skins = $total_cons_skins + $cons_skins;
                }
                elseif($category_id == 33)
                {
                    $cons_eyes = $count_token;
                    $total_cons_eyes = $total_cons_eyes + $cons_eyes;
                }
                elseif($category_id == 37)
                {
                    $svds = $count_token;
                    $total_svds = $total_svds + $svds;
                }
                elseif($category_id == 38)
                {
                    $dncs = $count_token;
                    $total_dncs = $total_dncs + $dncs;
                }
                elseif($category_id == 39)
                {
                    $usgs = $count_token;
                    $total_usgs = $total_usgs + $usgs;
                }
                elseif($category_id == 40)
                {
                    $admissions = $count_token;
                    $total_admissions = $total_admissions + $admissions;
                }
                elseif($category_id == 41)
                {
                    $gynaes = $count_token;
                    $total_gynaes = $total_gynaes + $gynaes;
                }
                elseif($category_id == 42)
                {
                    $emergency = $count_token;
                    $total_emergency = $total_emergency + $emergency;
                }
                elseif($category_id == 44)
                {
                    $ecg = $count_token;
                    $total_ecg = $total_ecg + $ecg;
                }
            }
        }

        $gynae_system = mysqli_num_rows(mysqli_query($con, "SELECT * FROM `gynae_register` WHERE doctor_id = '$doctor_id' AND created like '$date%' AND branch_id = '$br_id'"));
        $total_gynae_system = $total_gynae_system + $gynae_system;
        
        $refered = mysqli_num_rows(mysqli_query($con, "SELECT * FROM `referral_patients` WHERE `from_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND `referral_patient_created` like '$date%' AND branch_id = '$br_id' "));
        $total_refered = $total_refered + $refered;
        
        $refered_to = mysqli_num_rows(mysqli_query($con, "SELECT * FROM `referral_patients` WHERE `to_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND `referral_patient_created` like '$date%' "));
        $total_refered_to = $total_refered_to + $refered_to;

            $s++; ?>
        <tr>
            <td><?php echo $s; ?></td>
            <td><?php echo $row['doctor_id']; ?></td>
            <td><?php echo $row['tag_name']; ?></td>
            <td><?php echo $row['u_name']; ?></td>
            <td><?php echo $opd; ?></td>
            <td><?php echo $labs; ?></td>
            <td><?php 
                if($opd > 0 && $labs > 0)
                {   
                    if($opd >= $labs)
                    {
                        echo intval(($labs/$opd)*100);
                    }
                    else
                    {
                        echo '100';
                    }
                } 
                else 
                { 
                    echo '0';
                }
            ?></td>
            <td><?php echo $usgs; ?></td>
            <td><?php echo $svds; ?></td>
            <td><?php echo $dncs; ?></td>
            <td><?php echo $procedures; ?></td>
            <td><?php echo $cons_dentals; ?></td>
            <td><?php echo $skins; ?></td>
            <td><?php echo $eyes; ?></td>
            <td><?php echo $admissions; ?></td>
            <td><?php echo $emergency; ?></td>
            <td><?php echo $ecg; ?></td>
            <td><?php echo $gynaes; ?></td>
            <td><?php echo $gynae_system; ?></td>
            <td><?php echo $refered; ?></td>
            <td><?php echo $refered_to; ?></td>            
            <td style = "text-align: right;"><?php echo number_format((float)($cash ?? 0)); ?></td>
        </tr>
        <?php 
        $labs = 0;
        $labs_percentage = 0;
        $emergency = 0;
        $ecg = 0;
        $opds = 0;
        $cons_opds = 0;
        $labs = 0;
        $usgs = 0;
        $svds = 0;
        $dncs = 0;
        $procedures = 0;
        $cons_dentals = 0;
        $skins = 0;
        $eyes = 0;
        $admissions = 0;
        $emergency = 0;
        $ecg = 0;
        $gynaes = 0;
        $gynae_system = 0;
        $refered = 0;
        $refered_to = 0;
        }
    }
    ?>
        <tr style = "text-align: right;">
            <td><?php echo $count_run; ?></td>
            <td></td>
            <td></td>
            <td></td>
            <th><?php echo $total_opd; ?></th>
            <?php
            echo '<th>'.$total_lab.'</th>';
            echo '<th></th>';
            echo '<th>'.$total_usgs.'</th>
            <th>'.$total_svds.'</th></th>
            <th>'.$total_dncs.'</th>';
            echo '<th>'.$total_procedures.'</th>
            <th>'.$total_cons_dentals.'</th>
            <th>'.$total_skins.'</th>
            <th>'.$total_eyes.'</th>
            <th>'.$total_admissions.'</th>
            <th>'.$total_emergency.'</th>
            <th>'.$total_ecg.'</th>
            <th>'.$total_gynaes.'</th>';
            ?>
            <th><?php echo $total_gynae_system; ?></th>
            <th><?php echo $total_refered; ?></th>
            <th><?php echo $total_refered_to; ?></th>
            <th><?php echo number_format((float)($total_cash ?? 0)); ?></th>
        </tr>
    </tbody>
</table>
</body>
</html>
<?php mysqli_close($con); ?>