<?php
include 'includes/connect.php';
require_once __DIR__ . '/../bk/includes/progress_report_params.php';

$req = progress_report_resolve_request($con);
$date = $req['date'];
$br_id = $req['br_id'];
$like = $req['like'];

$opds = progress_opd_count_by_doctor($con, $br_id, $like);
$cons_opds = progress_item_count_by_doctor($con, $br_id, $like, '489');
$admissions = progress_item_count_by_doctor($con, $br_id, $like, '444, 448, 452, 456, 460, 945, 1124, 1125, 1128, 1131, 1132, 1145, 1186, 1285, 1289, 1293, 1297, 1301');
$svds = progress_item_count_by_doctor($con, $br_id, $like, '472, 1118, 1313');
$dncs = progress_item_count_by_doctor($con, $br_id, $like, '473, 1119, 1314');
$usgs = progress_item_count_by_doctor($con, $br_id, $like, '1138, 1185, 476, 477, 478, 1161, 1162, 1163, 1184, 1317, 1318');
$procedures = progress_item_count_by_doctor($con, $br_id, $like, '(SELECT id FROM items WHERE id NOT IN (473, 1119, 1314, 472, 1118, 1313) AND category_id = 3)');
$lab_stats = progress_lab_stats_by_doctor($con, $br_id, $like);

$doctor_sql = "SELECT DISTINCT doctor_id FROM tokans WHERE created LIKE '$like' AND branch_id = '$br_id' ORDER BY doctor_id";
$doctor_ids = array();
$run = mysqli_query($con, $doctor_sql);
if ($run) {
    while ($row = mysqli_fetch_assoc($run)) {
        $doctor_ids[] = (int) $row['doctor_id'];
    }
}

$user_names = array();
if (count($doctor_ids) > 0) {
    $ids = implode(',', $doctor_ids);
    $run_names = mysqli_query($con, "SELECT id, u_name FROM users WHERE id IN ($ids)");
    if ($run_names) {
        while ($row = mysqli_fetch_assoc($run_names)) {
            $user_names[(int) $row['id']] = $row['u_name'];
        }
    }
}
?>
<html>
<head>
    <title>PRINT PROGRESS REPORT</title>
</head>
<body>

<table border="solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS DATE <?php echo date_format(date_create($date), ' d F Y'); ?></h3>
    <h5 align="center">GENERATED BY: <i><?php echo htmlspecialchars($user_name, ENT_QUOTES, 'UTF-8'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th><th>NAME</th><th>OPD</th><th>CONS</th><th>LAB</th><th>USG</th>
            <th>SVD</th><th>D&amp;C</th><th>PROCEDURE</th><th>ADMISSION</th>
        </tr>
    </thead>
<?php
$s = 0;
$totals = array('opds' => 0, 'cons' => 0, 'lab' => 0, 'usg' => 0, 'svd' => 0, 'dnc' => 0, 'proc' => 0, 'adm' => 0);

if (count($doctor_ids) > 0) {
    echo '<tbody>';
    foreach ($doctor_ids as $doctor) {
        $s++;
        $opd = $opds[$doctor] ?? 0;
        $cons = $cons_opds[$doctor] ?? 0;
        $adm = $admissions[$doctor] ?? 0;
        $svd = $svds[$doctor] ?? 0;
        $dnc = $dncs[$doctor] ?? 0;
        $usg = $usgs[$doctor] ?? 0;
        $proc = $procedures[$doctor] ?? 0;
        $lab_cash = $lab_stats[$doctor]['cash'] ?? 0;
        $labs = ($lab_cash == 0) ? 'N/A' : $lab_cash;

        $totals['opds'] += $opd;
        $totals['cons'] += $cons;
        $totals['lab'] += is_numeric($labs) ? $labs : 0;
        $totals['usg'] += $usg;
        $totals['svd'] += $svd;
        $totals['dnc'] += $dnc;
        $totals['proc'] += $proc;
        $totals['adm'] += $adm;

        $doctor_name = $user_names[$doctor] ?? get_uname_by_id($doctor);
        echo '<tr style="text-align: right;">';
        echo '<td>' . $s . '</td>';
        echo '<td style="text-align: left;">' . htmlspecialchars($doctor_name, ENT_QUOTES, 'UTF-8') . '</td>';
        echo '<td>' . $opd . '</td><td>' . $cons . '</td><td>' . $labs . '</td><td>' . $usg . '</td>';
        echo '<td>' . $svd . '</td><td>' . $dnc . '</td><td>' . $proc . '</td><td>' . $adm . '</td>';
        echo '</tr>';
    }
    echo '</tbody><tfoot><tr style="text-align: right;"><th></th><th></th>';
    echo '<th>' . $totals['opds'] . '</th><th>' . $totals['cons'] . '</th><th>' . $totals['lab'] . '</th>';
    echo '<th>' . $totals['usg'] . '</th><th>' . $totals['svd'] . '</th><th>' . $totals['dnc'] . '</th>';
    echo '<th>' . $totals['proc'] . '</th><th>' . $totals['adm'] . '</th></tr></tfoot>';
}
?>
</table>
</body>
</html>
<?php mysqli_close($con); ?>
