<?php
require_once __DIR__ . '/includes/connect_report.php';
require_once __DIR__ . '/../includes/hr_monthly_progress_doctor_helpers.php';

@set_time_limit(300);
if (function_exists('ini_set')) {
    @ini_set('max_execution_time', '300');
}

$date = '';
$br_id = 0;
if (isset($_GET['date']) && $_GET['date'] !== '') {
    $date = (string) $_GET['date'];
    $br_id = (int) ($_GET['br_id'] ?? 0);
} elseif (isset($_POST['date']) && $_POST['date'] !== '') {
    $date = (string) $_POST['date'];
    $br_id = (int) ($_POST['br_id'] ?? 0);
}

if ($date === '' || $br_id < 1) {
    http_response_code(400);
    exit('Branch and month are required.');
}

header('Content-Type: text/html; charset=utf-8');
echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Monthly Progress</title></head><body><p>Generating monthly progress report…</p>';
if (function_exists('ob_flush')) {
    @ob_flush();
}
@flush();

$doctorRows = hr_monthly_progress_doctor_rows($con, $br_id, $date);
$branchHeader = summary_branch_header($con, $br_id, $company_name);
$monthLabel = ycdo_safe_date_format(strlen($date ?? '') === 7 ? $date . '-01' : $date, 'F Y', $date);
$generatedBy = htmlspecialchars($hr_name, ENT_QUOTES, 'UTF-8');

$totals = hr_monthly_progress_doctor_empty_row();
$count_run = count($doctorRows);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @media print { .noprint { visibility: hidden; } }
        table { border-collapse: collapse; width: 100%; font-size: 12px; }
        th, td { border: 1px solid #333; padding: 3px; }
    </style>
    <title><?php echo htmlspecialchars($branchHeader['name'] . ' ' . $monthLabel); ?> MONTHLY PROGRESS REPORT</title>
</head>
<body>
<div class="noprint"><a href="dashboard.php">GOTO DASHBOARD</a></div>

<table border="solid">
<caption>
    <h2><?php echo htmlspecialchars($company_name); ?></h2>
    <h2><?php echo htmlspecialchars($branchHeader['name']); ?></h2>
    <h3>PROGRESS MONTH <?php echo htmlspecialchars($monthLabel); ?></h3>
    <h5 align="center">PROGRESS REPORT IS GENERATED BY: <i><?php echo $generatedBy; ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
<thead>
    <tr>
        <th>S#</th><th>ID</th><th>BRANCH</th><th>NAME</th><th>OPD</th><th>LAB</th><th>LAB%</th><th>CASH</th>
        <th>USG</th><th>SVD</th><th>D&amp;C</th><th>OPERATION</th><th>DENTAL</th><th>SKIN</th><th>EYE</th>
        <th>ADMISSION</th><th>EMERGENCY</th><th>ECG</th><th>GYNAE TOKEN</th><th>GYNAE</th><th>REF. BY</th><th>REF. TO</th><th>COLLECTION</th>
    </tr>
</thead>
<tbody>
<?php
$s = 0;
foreach ($doctorRows as $row) {
    $s++;
    $opd = (int) $row['opd'];
    $tests = (int) $row['tests'];
    $totals['opd'] += $opd;
    $totals['tests'] += $tests;
    $totals['lab_test_cash'] += (float) $row['lab_test_cash'];
    $totals['procedures'] += (int) $row['procedures'];
    $totals['consultants'] += (int) $row['consultants'];
    $totals['dentals'] += (int) $row['dentals'];
    $totals['skins'] += (int) $row['skins'];
    $totals['eyes'] += (int) $row['eyes'];
    $totals['physiotherapies'] += (int) $row['physiotherapies'];
    $totals['minir_procedures'] += (int) $row['minir_procedures'];
    $totals['svds'] += (int) $row['svds'];
    $totals['dncs'] += (int) $row['dncs'];
    $totals['usgs'] += (int) $row['usgs'];
    $totals['admissions'] += (int) $row['admissions'];
    $totals['gyneas'] += (int) $row['gyneas'];
    $totals['emergency'] += (int) $row['emergency'];
    $totals['ecgs'] += (int) $row['ecgs'];
    $totals['gynae_system'] += (int) $row['gynae_system'];
    $totals['refered'] += (int) $row['refered'];
    $totals['refered_to'] += (int) $row['refered_to'];
    $totals['cash'] += (float) $row['cash'];
    ?>
    <tr>
        <td><?php echo $s; ?></td>
        <td><?php echo (int) $row['doctor_id']; ?></td>
        <td><?php echo htmlspecialchars($row['tag_name']); ?></td>
        <td><?php echo htmlspecialchars($row['u_name']); ?></td>
        <td><?php echo $opd; ?></td>
        <td><?php echo $tests; ?></td>
        <td><?php echo hr_monthly_progress_lab_percent($opd, $tests); ?></td>
        <td><?php echo number_format((float)((float) $row['lab_test_cash'] ?? 0)); ?></td>
        <td><?php echo (int) $row['usgs']; ?></td>
        <td><?php echo (int) $row['svds']; ?></td>
        <td><?php echo (int) $row['dncs']; ?></td>
        <td><?php echo (int) $row['procedures']; ?></td>
        <td><?php echo (int) $row['consultants']; ?></td>
        <td><?php echo (int) $row['skins']; ?></td>
        <td><?php echo (int) $row['eyes']; ?></td>
        <td><?php echo (int) $row['admissions']; ?></td>
        <td><?php echo (int) $row['emergency']; ?></td>
        <td><?php echo (int) $row['ecgs']; ?></td>
        <td><?php echo (int) $row['gyneas']; ?></td>
        <td><?php echo (int) $row['gynae_system']; ?></td>
        <td><?php echo (int) $row['refered']; ?></td>
        <td><?php echo (int) $row['refered_to']; ?></td>
        <td style="text-align:right;"><?php echo number_format((float)((float) $row['cash'] ?? 0)); ?></td>
    </tr>
    <?php
}
?>
    <tr style="text-align:right;">
        <th><?php echo $count_run; ?></th>
        <th colspan="3"></th>
        <th><?php echo (int) $totals['opd']; ?></th>
        <th><?php echo (int) $totals['tests']; ?></th>
        <th></th>
        <th><?php echo number_format((float)((float) $totals['lab_test_cash'] ?? 0)); ?></th>
        <th><?php echo (int) $totals['usgs']; ?></th>
        <th><?php echo (int) $totals['svds']; ?></th>
        <th><?php echo (int) $totals['dncs']; ?></th>
        <th><?php echo (int) $totals['procedures']; ?></th>
        <th><?php echo (int) $totals['consultants']; ?></th>
        <th><?php echo (int) $totals['skins']; ?></th>
        <th><?php echo (int) $totals['eyes']; ?></th>
        <th><?php echo (int) $totals['admissions']; ?></th>
        <th><?php echo (int) $totals['emergency']; ?></th>
        <th><?php echo (int) $totals['ecgs']; ?></th>
        <th><?php echo (int) $totals['gyneas']; ?></th>
        <th><?php echo (int) $totals['gynae_system']; ?></th>
        <th><?php echo (int) $totals['refered']; ?></th>
        <th><?php echo (int) $totals['refered_to']; ?></th>
        <th><?php echo number_format((float)((float) $totals['cash'] ?? 0)); ?></th>
    </tr>
</tbody>
</table>
</body>
</html>
<?php
if ($con instanceof mysqli) {
    mysqli_close($con);
}
