<?php 
include 'includes/connect.php'; 
if(isset($_GET['date']))
{
    $date = $_GET['date'];
    $br_id = $_GET['br_id'];
}
elseif(isset($_POST['date']))
{
    $date = $_POST['date'];
    $br_id = $_POST['br_id'];
}
else
{
    exit(0);
}

// Optimization: Calculate date boundaries to use fast index lookups instead of LIKE
$start_date = $date . ' 00:00:00';
$end_date   = $date . ' 23:59:59';

?>
<html>
<head>
    <style>
        @media print {
           .noprint {
              visibility: hidden;
           }
        }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid black; padding: 5px; text-align: center; }
    </style>
    <title><?php echo get_branch_tag_by($br_id)." ";echo date_format(date_create($date), "m-Y"); ?> DAILY PROGRESS REPORT </title>
</head>
<body>
<div>
    <a class = "noprint" href = "dashboard.php">GOTO DASHBOARD</a>
</div>
    
<table>
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS DATE <?php echo date_format(date_create($date), " d-m-Y"); ?></h3>
    <h5 align = "center">PROGRESS REPORT IS GENERATED BY: <i><?php echo $bk_name; ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>ID</th>
            <th>BRANCH</th>
            <th>NAME</th>
            <th>OPD</th>
            <th>Dia.Pt</th>
            <th>LAB</th>
            <th>LAB%</th>
            <th>CASH</th>
            <th>USG</th>
            <th>SVD</th>
            <th>D&C</th>
            <th>OPERATION</th>
            <th>DENTAL</th>
            <th>SKIN</th>
            <th>EYE</th>
            <th>ADMISSION</th>
            <th>EMERGENCY</th>
            <th>ECG</th>
            <th>GYNAE TOKEN</th>
            <th>GYNAE</th>
            <th>REF. BY</th>
            <th>REF. TO</th>
            <th>COLLECTION</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $s = 0; 
    $total_opd = 0;
    $total_cash = 0;
    $total_dia_patients = 0;
    $total_lab_test_cash = 0;
    
    $total_tests = 0;
    $total_procedures = 0;
    $total_consultants = 0;
    $total_dentals = 0;
    $total_skins = 0;
    $total_eyes = 0;
    $total_physiotherapies = 0;
    $total_minir_procedures = 0;
    $total_svds = 0;
    $total_dncs = 0;
    $total_usgs = 0;
    $total_admissions = 0;
    $total_gyneas = 0;
    $total_emergency = 0;
    $total_ecgs = 0;
    $total_gynae_system = 0;
    $total_refered = 0;
    $total_refered_to = 0;

    // Main query optimized to utilize datetime indexing range
    $select = "SELECT DISTINCT tokans.doctor_id, users.u_name , branchs.tag_name, 
               COUNT(CASE WHEN tokans.tokan_type_id <= 100 THEN tokans.tokan_type_id END) AS opd, 
               SUM(cash) AS cash_collection 
               FROM `tokans` 
               INNER JOIN users ON tokans.doctor_id = users.id 
               INNER JOIN branchs ON users.branch_id = branchs.id 
               WHERE tokans.created BETWEEN '$start_date' AND '$end_date' 
                 AND tokans.branch_id = '$br_id' 
                 AND tokans.status = '1' 
               GROUP BY tokans.doctor_id 
               ORDER BY tokans.doctor_id";
               
    $run = mysqli_query($con, $select);
    $count_run = mysqli_num_rows($run);
    
    if($count_run > 0)
    {
        while($row = mysqli_fetch_array($run))
        {
            $doctor_id = $row['doctor_id'];
            $opd = $row['opd'];
            $cash_collection = $row['cash_collection'];
            
            $total_opd += $opd;
            $total_cash += $cash_collection;

            // 1. Optimized Diagnostic Patients Query
            $dia_patients = "SELECT COUNT(DISTINCT tokan_no) as count_dia, SUM(sale_price) as sum_cash 
                             FROM `item_by_doctor` 
                             WHERE `category_id` = '2' 
                               AND branch_id = '$br_id' 
                               AND created BETWEEN '$start_date' AND '$end_date' 
                               AND doctor_id = '$doctor_id'"; 
            $run_dia_patients = mysqli_query($con, $dia_patients);
            $row_dia_patients = mysqli_fetch_assoc($run_dia_patients);
            
            $count_dia_patients = $row_dia_patients['count_dia'] ?? 0;
            $count_dia_patient_cash = $row_dia_patients['sum_cash'] ?? 0;
            
            $total_dia_patients += $count_dia_patients;
            $total_lab_test_cash += $count_dia_patient_cash;

            // 2. Optimized Main Items Matrix Query
            $select_data = "SELECT
                COUNT(CASE WHEN category_id = 2 THEN 1 END) as tests,
                COUNT(CASE WHEN category_id = 3 THEN 1 END) as procedures,
                COUNT(CASE WHEN category_id = 29 THEN 1 END) as consultants,
                COUNT(CASE WHEN category_id = 31 THEN 1 END) as dentals,
                COUNT(CASE WHEN category_id = 32 THEN 1 END) as skins,
                COUNT(CASE WHEN category_id = 33 THEN 1 END) as eyes,
                COUNT(CASE WHEN category_id = 34 THEN 1 END) as physiotherapies,
                COUNT(CASE WHEN category_id = 36 THEN 1 END) as minir_procedures,
                COUNT(CASE WHEN category_id = 37 THEN 1 END) as svds,
                COUNT(CASE WHEN category_id = 38 THEN 1 END) as dncs,
                COUNT(CASE WHEN category_id = 39 THEN 1 END) as usgs,
                COUNT(CASE WHEN category_id = 40 THEN 1 END) as admissions,
                COUNT(CASE WHEN category_id = 41 THEN 1 END) as gyneas,
                COUNT(CASE WHEN category_id = 42 THEN 1 END) as emergency,
                COUNT(CASE WHEN category_id = 44 THEN 1 END) as ecgs
            FROM `item_by_doctor` 
            WHERE created BETWEEN '$start_date' AND '$end_date' 
              AND doctor_id = '$doctor_id' 
              AND branch_id = '$br_id' 
              AND category_id IN(2, 3, 29, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 44)";
              
            $run_data = mysqli_query($con, $select_data);
            $row_data = mysqli_fetch_assoc($run_data);

            $tests = $row_data['tests'] ?? 0;
            $procedures = $row_data['procedures'] ?? 0;
            $consultants = $row_data['consultants'] ?? 0;
            $dentals = $row_data['dentals'] ?? 0;
            $skins = $row_data['skins'] ?? 0;
            $eyes = $row_data['eyes'] ?? 0;
            $physiotherapies = $row_data['physiotherapies'] ?? 0;
            $minir_procedures = $row_data['minir_procedures'] ?? 0;
            $svds = $row_data['svds'] ?? 0;
            $dncs = $row_data['dncs'] ?? 0;
            $usgs = $row_data['usgs'] ?? 0;
            $admissions = $row_data['admissions'] ?? 0;
            $gyneas = $row_data['gyneas'] ?? 0;
            $emergency = $row_data['emergency'] ?? 0;
            $ecgs = $row_data['ecgs'] ?? 0;

            $total_tests += $tests;
            $total_procedures += $procedures;
            $total_consultants += $consultants;
            $total_dentals += $dentals;
            $total_skins += $skins;
            $total_eyes += $eyes;
            $total_physiotherapies += $physiotherapies;
            $total_minir_procedures += $minir_procedures;
            $total_svds += $svds;
            $total_dncs += $dncs;
            $total_usgs += $usgs;
            $total_admissions += $admissions;
            $total_gyneas += $gyneas;
            $total_emergency += $emergency;
            $total_ecgs += $ecgs;

            // 3. Optimized Registry Counts using COUNT(*) instead of loading full rows via mysqli_num_rows
            $gynae_res = mysqli_query($con, "SELECT COUNT(*) as total FROM `gynae_register` WHERE doctor_id = '$doctor_id' AND created BETWEEN '$start_date' AND '$end_date' AND branch_id = '$br_id'");
            $gynae_system = mysqli_fetch_assoc($gynae_res)['total'];
            $total_gynae_system += $gynae_system;
            
            $ref_from_res = mysqli_query($con, "SELECT COUNT(*) as total FROM `referral_patients` WHERE `from_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND `referral_patient_created` BETWEEN '$start_date' AND '$end_date' AND branch_id = '$br_id'");
            $refered = mysqli_fetch_assoc($ref_from_res)['total'];
            $total_refered += $refered;
            
            // Note: referral_to does not check branch_id in your original code; preserved as requested
            $ref_to_res = mysqli_query($con, "SELECT COUNT(*) as total FROM `referral_patients` WHERE `to_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND `referral_patient_created` BETWEEN '$start_date' AND '$end_date'");
            $refered_to = mysqli_fetch_assoc($ref_to_res)['total'];
            $total_refered_to += $refered_to;

            $s++; 
            ?>
        <tr>
            <td><?php echo $s; ?></td>
            <td><?php echo $doctor_id; ?></td>
            <td><?php echo $row['tag_name']; ?></td>
            <td><?php echo $row['u_name']; ?></td>
            <td><?php echo $opd; ?></td>
            <td><?php echo $count_dia_patients; ?></td>
            <td><?php echo $tests; ?></td>
            <td>
                <?php 
                if($opd > 0 && $count_dia_patients > 0) {   
                    echo ($opd >= $count_dia_patients) ? intval(($count_dia_patients/$opd)*100) : '100';
                } else { 
                    echo '0';
                }
                ?>
            </td>
            <td><?php echo number_format($count_dia_patient_cash); ?></td>
            <td><?php echo $usgs; ?></td>
            <td><?php echo $svds; ?></td>
            <td><?php echo $dncs; ?></td>
            <td><?php echo $procedures; ?></td>
            <td><?php echo $consultants; ?></td>
            <td><?php echo $skins; ?></td>
            <td><?php echo $eyes; ?></td>
            <td><?php echo $admissions; ?></td>
            <td><?php echo $emergency; ?></td>
            <td><?php echo $ecgs; ?></td>
            <td><?php echo $gyneas; ?></td>
            <td><?php echo $gynae_system; ?></td>
            <td><?php echo $refered; ?></td>
            <td><?php echo $refered_to; ?></td>            
            <td style="text-align: right;"><?php echo number_format($cash_collection); ?></td>
        </tr>
        <?php 
        }
    }
    ?>
        <tr style="text-align: right; font-weight: bold;">
            <td><?php echo $count_run; ?></td>
            <td></td>
            <td></td>
            <td></td>
            <td><?php echo $total_opd; ?></td>
            <td><?php echo $total_dia_patients; ?></td>
            <td><?php echo $total_tests; ?></td>
            <td></td>
            <td><?php echo number_format($total_lab_test_cash); ?></td>
            <td><?php echo $total_usgs; ?></td>
            <td><?php echo $total_svds; ?></td>
            <td><?php echo $total_dncs; ?></td>
            <td><?php echo $total_procedures; ?></td>
            <td><?php echo $total_consultants; ?></td>
            <td><?php echo $total_skins; ?></td>
            <td><?php echo $total_eyes; ?></td>
            <td><?php echo $total_admissions; ?></td>
            <td><?php echo $total_emergency; ?></td>
            <td><?php echo $total_ecgs; ?></td>
            <td><?php echo $total_gyneas; ?></td>
            <td><?php echo $total_gynae_system; ?></td>
            <td><?php echo $total_refered; ?></td>
            <td><?php echo $total_refered_to; ?></td>
            <td><?php echo number_format($total_cash); ?></td>
        </tr>
    </tbody>
</table>
</body>
</html>
<?php mysqli_close($con); ?>