<?php
// OPTIMIZED: replaced per-row queries with pre-aggregated batch queries
include 'includes/connect.php';
require_once __DIR__ . '/includes/progress_report_params.php';

set_time_limit(120);

if(isset($_GET['date']))
{
    $date = $_GET['date'];
    $br_id = (int) $_GET['br_id'];
}
elseif(isset($_POST['date']))
{
    $date = $_POST['date'];
    $br_id = (int) $_POST['br_id'];
}
else
{
    exit(0);
}

$like = mysqli_real_escape_string($con, (string) $date) . '%';
$cash_map = progress_cash_sum_by_doctor($con, $br_id, $like);
$dia_stats = progress_dia_patient_stats_by_doctor($con, $br_id, $like);
$item_rows = progress_item_row_counts_by_doctor($con, $br_id, $like);
$gynae_system_map = progress_gynae_register_count_by_doctor($con, $br_id, $like);
$refer_from = progress_referral_from_count_by_branch($con, $br_id, $like);
$refer_to = progress_referral_to_count_by_doctor($con, $like);
?>
<html>
<head>
    <style>
        @media print {
           .noprint {
              visibility: hidden;
           }
        }
    </style>
    <title><?php echo get_branch_tag_by($br_id)." ";echo date_format(date_create($date), "m-Y"); ?> MONTHLY PROGRESS REPORT </title>
</head>
<body>
<div>
    <a class = "noprint" href = "dashboard.php">GOTO DASHBOARD</a>
</div>
    
<table border = "solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS MONTH <?php echo date_format(date_create($date), " F Y"); ?></h3>
    <h5 align = "center">PROGRESS REPORT IS GENERATED BY: <i><?php echo $bk_name; ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>ID</th>
            <th>BRANCH</th>
            <th>NAME</th>
            <th>OPD</th>
            <th>Dia.Pt</th>
            <th>LAB</th>
            <th>LAB%</th>
            <th>CASH</th>
            <th>USG</th>
            <th>SVD</th>
            <th>D&C</th>
            <th>OPERATION</th>
            <th>DENTAL</th>
            <th>SKIN</th>
            <th>EYE</th>
            <th>ADMISSION</th>
            <th>EMERGENCY</th>
            <th>ECG</th>
            <th>GYNAE TOKEN</th>
            <th>GYNAE</th>
            <th>REF. BY</th>
            <th>REF. TO</th>
            <th>COLLECTION</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $total_patients = 0;
    $total_refered = 0;
    $total_refered_to = 0;
    $total_opd = 0;
    $total_cash = 0;
    $total_dia_patients = 0;
    $total_gynae_system = 0;
    $s = 0; 
    
    $tests = 0;
    $lab_test_cash = 0;
    $procedures = 0;
    $consultants = 0;
    $dentals = 0;
    $skins = 0;
    $eyes = 0;
    $physiotherapies = 0;
    $minir_procedures = 0;
    $svds = 0;
    $dncs = 0;
    $usgs = 0;
    $admissions = 0;
    $gyneas = 0;
    $emergency = 0;
    $ecgs = 0;
    
    $total_tests = 0;
    $total_lab_test_cash = 0;
    $total_procedures = 0;
    $total_consultants = 0;
    $total_dentals = 0;
    $total_skins = 0;
    $total_eyes = 0;
    $total_physiotherapies = 0;
    $total_minir_procedures = 0;
    $total_svds = 0;
    $total_dncs = 0;
    $total_usgs = 0;
    $total_admissions = 0;
    $total_gyneas = 0;
    $total_emergency = 0;
    $total_ecgs = 0;
    
    $tok_date_clause = progress_sql_date_clause($con, $like, 'tokans.created');
    $select = "SELECT DISTINCT tokans.doctor_id, users.u_name , branchs.tag_name, COUNT(CASE WHEN tokans.tokan_type_id <= 100 THEN tokans.tokan_type_id END) AS opd FROM `tokans` INNER JOIN users ON tokans.doctor_id = users.id INNER JOIN branchs ON users.branch_id = branchs.id WHERE $tok_date_clause AND tokans.branch_id = '$br_id' AND tokans.status = '1' GROUP BY tokans.doctor_id ORDER BY tokans.doctor_id ";
    $run = mysqli_query($con, $select);
    $count_run = mysqli_num_rows($run);
    if(mysqli_num_rows($run) > 0)
    {
        while($row = mysqli_fetch_array($run))
        {
            $opd = $row['opd'];
            $total_opd = $total_opd + $opd;
            $doctor_id = (int) $row['doctor_id'];
            $cash = $cash_map[$doctor_id] ?? 0;
            $total_cash = $total_cash + $cash;

            $dia_row = $dia_stats[$doctor_id] ?? array('count' => 0, 'cash' => 0.0);
            $count_dia_patients = $dia_row['count'];
            $lab_test_cash = $dia_row['cash'];
            $total_dia_patients = $total_dia_patients + $count_dia_patients;
            $total_lab_test_cash = $total_lab_test_cash + $lab_test_cash;

            $row_data = $item_rows[$doctor_id] ?? array();
            $tests = (int) ($row_data['tests'] ?? 0);
            $total_tests = $total_tests + $tests;
            $procedures = (int) ($row_data['procedures'] ?? 0);
            $total_procedures = $total_procedures + $procedures;
            $consultants = (int) ($row_data['consultants'] ?? 0);
            $total_consultants = $total_consultants + $consultants;
            $dentals = (int) ($row_data['dentals'] ?? 0);
            $total_dentals = $total_dentals + $dentals;
            $skins = (int) ($row_data['skins'] ?? 0);
            $total_skins = $total_skins + $skins;
            $eyes = (int) ($row_data['eyes'] ?? 0);
            $total_eyes = $total_eyes + $eyes;
            $physiotherapies = (int) ($row_data['physiotherapies'] ?? 0);
            $total_physiotherapies = $total_physiotherapies + $physiotherapies;
            $minir_procedures = (int) ($row_data['minir_procedures'] ?? 0);
            $total_minir_procedures = $total_minir_procedures + $minir_procedures;
            $svds = (int) ($row_data['svds'] ?? 0);
            $total_svds = $total_svds + $svds;
            $dncs = (int) ($row_data['dncs'] ?? 0);
            $total_dncs = $total_dncs + $dncs;
            $usgs = (int) ($row_data['usgs'] ?? 0);
            $total_usgs = $total_usgs + $usgs;
            $admissions = (int) ($row_data['admissions'] ?? 0);
            $total_admissions = $total_admissions + $admissions;
            $gyneas = (int) ($row_data['gyneas'] ?? 0);
            $total_gyneas = $total_gyneas + $gyneas;
            $emergency = (int) ($row_data['emergency'] ?? 0);
            $total_emergency = $total_emergency + $emergency;
            $ecgs = (int) ($row_data['ecgs'] ?? 0);
            $total_ecgs = $total_ecgs + $ecgs;

            $gynae_system = $gynae_system_map[$doctor_id] ?? 0;
            $total_gynae_system = $total_gynae_system + $gynae_system;
            $refered = $refer_from[$doctor_id] ?? 0;
            $total_refered = $total_refered + $refered;
            $refered_to = $refer_to[$doctor_id] ?? 0;
            $total_refered_to = $total_refered_to + $refered_to;

            $s++; ?>
        <tr>
            <td><?php echo $s; ?></td>
            <td><?php echo $row['doctor_id']; ?></td>
            <td><?php echo $row['tag_name']; ?></td>
            <td><?php echo $row['u_name']; ?></td>
            <td><?php echo $opd; ?></td>
            <td><?php echo $count_dia_patients; ?></td>
            <td><?php echo $tests; ?></td>
            <td>
                <?php 
                if($opd > 0 && $count_dia_patients > 0)
                {   
                    if($opd >= $count_dia_patients)
                    {
                        echo intval(($count_dia_patients/$opd)*100);
                    }
                    else
                    {
                        echo '100';
                    }
                } 
                else 
                { 
                    echo '0';
                }
                ?>
            </td>
            <td><?php echo number_format((float)($lab_test_cash ?? 0)); ?></td>
            <td><?php echo $usgs; ?></td>
            <td><?php echo $svds; ?></td>
            <td><?php echo $dncs; ?></td>
            <td><?php echo $procedures; ?></td>
            <td><?php echo $consultants; ?></td>
            <td><?php echo $skins; ?></td>
            <td><?php echo $eyes; ?></td>
            <td><?php echo $admissions; ?></td>
            <td><?php echo $emergency; ?></td>
            <td><?php echo $ecgs; ?></td>
            <td><?php echo $gyneas; ?></td>
            <td><?php echo $gynae_system; ?></td>
            <td><?php echo $refered; ?></td>
            <td><?php echo $refered_to; ?></td>            
            <td style = "text-align: right;"><?php echo number_format((float)($cash ?? 0)); ?></td>
        </tr>
        <?php 
        $tests = 0;
        $lab_test_cash = 0;
        $procedures = 0;
        $consultants = 0;
        $dentals = 0;
        $skins = 0;
        $eyes = 0;
        $physiotherapies = 0;
        $minir_procedures = 0;
        $svds = 0;
        $dncs = 0;
        $usgs = 0;
        $admissions = 0;
        $gyneas = 0;
        $emergency = 0;
        $ecgs = 0;
        $gynaes = 0;
        $gynae_system = 0;
        $refered = 0;
        $refered_to = 0;
        }
    }
    ?>
        <tr style = "text-align: right;">
            <td><?php echo $count_run; ?></td>
            <td></td>
            <td></td>
            <td></td>
            <th><?php echo $total_opd; ?></th>
            <?php
            echo '<th>'.$total_dia_patients.'</th>';
            echo '<th>'.$total_tests.'</th>';
            echo '<th></th>';
            echo '<th>'.number_format((float)($total_lab_test_cash ?? 0)).'</th>';
            echo '<th>'.$total_usgs.'</th>
            <th>'.$total_svds.'</th></th>
            <th>'.$total_dncs.'</th>';
            echo '<th>'.$total_procedures.'</th>
            <th>'.$total_consultants.'</th>
            <th>'.$total_skins.'</th>
            <th>'.$total_eyes.'</th>
            <th>'.$total_admissions.'</th>
            <th>'.$total_emergency.'</th>
            <th>'.$total_ecgs.'</th>
            <th>'.$total_gyneas.'</th>';
            ?>
            <th><?php echo $total_gynae_system; ?></th>
            <th><?php echo $total_refered; ?></th>
            <th><?php echo $total_refered_to; ?></th>
            <th><?php echo number_format((float)($total_cash ?? 0)); ?></th>
        </tr>
    </tbody>
</table>
</body>
</html>
<?php mysqli_close($con); ?>