<?php 
include 'includes/connect.php'; 
if(isset($_GET['date']))
{
    $date = $_GET['date'];
    $start_from = $_GET['start_from'];
    $end_at = $_GET['end_at'];
    $br_id = $_GET['br_id'];
}
elseif(isset($_POST['date']))
{
    $date = $_POST['date'];
    $start_from = $_POST['start_from'];
    $end_at = $_POST['end_at'];
    $br_id = $_POST['br_id'];
}
else
{
    exit(0);
}
?>
<html>
<head>
    <style>
        @media print {
           .noprint {
              visibility: hidden;
           }
        }
    </style>
    <title><?php echo get_branch_tag_by($br_id)." ";echo date_format(date_create($date), "m-Y"); ?> DAILY PROGRESS REPORT </title>
</head>
<body>
<div>
    <a class = "noprint" href = "dashboard.php">GOTO DASHBOARD</a>
</div>
    
<table border = "solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS DATE <?php echo date_format(date_create($date), " d-m-Y"); ?></h3>
    <h5 align = "center">PROGRESS REPORT IS GENERATED BY: <i><?php echo $bk_name; ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>ID</th>
            <th>BRANCH</th>
            <th>NAME</th>
            <th>OPD</th>
            <th>Dia.Pt</th>
            <th>LAB</th>
            <th>LAB%</th>
            <th>CASH</th>
            <th>USG</th>
            <th>SVD</th>
            <th>D&C</th>
            <th>OPERATION</th>
            <th>DENTAL</th>
            <th>SKIN</th>
            <th>EYE</th>
            <th>ADMISSION</th>
            <th>EMERGENCY</th>
            <th>ECG</th>
            <th>GYNAE TOKEN</th>
            <th>GYNAE</th>
            <th>REF. BY</th>
            <th>REF. TO</th>
            <th>COLLECTION</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $total_refered = 0;
    $total_refered_to = 0;

    $s = 0; 
    $cash_collection = 0;
    $tests = 0;
    $procedures = 0;
    $consultants = 0;
    $dentals = 0;
    $skins = 0;
    $eyes = 0;
    $physiotherapies = 0;
    $minir_procedures = 0;
    $svds = 0;
    $dncs = 0;
    $usgs = 0;
    $admissions = 0;
    $gyneas = 0;
    $emergency = 0;
    $ecgs = 0;
    
    $total_tests = 0;
    $total_lab_test_cash = 0;
    $total_procedures = 0;
    $total_consultants = 0;
    $total_dentals = 0;
    $total_skins = 0;
    $total_eyes = 0;
    $total_physiotherapies = 0;
    $total_minir_procedures = 0;
    $total_svds = 0;
    $total_dncs = 0;
    $total_usgs = 0;
    $total_admissions = 0;
    $total_gyneas = 0;
    $total_emergency = 0;
    $total_ecgs = 0;
    
    $select = "SELECT DISTINCT tokans.doctor_id, users.u_name , branchs.tag_name, COUNT(CASE WHEN tokans.tokan_type_id <= 100 THEN tokans.tokan_type_id END) AS opd, SUM(cash) AS cash_collection FROM `tokans` INNER JOIN users ON tokans.doctor_id = users.id INNER JOIN branchs ON users.branch_id = branchs.id WHERE tokans.created >= '$date $start_from' AND tokans.created <= '$date $end_at' AND tokans.branch_id = '$br_id' AND tokans.status = '1' GROUP BY tokans.doctor_id ORDER BY tokans.doctor_id ";
    $run = mysqli_query($con, $select);
    $count_run = mysqli_num_rows($run);
    if(mysqli_num_rows($run) > 0)
    {
        while($row = mysqli_fetch_array($run))
        {
            $patients = 0;
            $opd = $row['opd'];
            $total_opd = $total_opd + $opd;
            $cash_collection = $row['cash_collection'];
            $total_cash = $total_cash + $cash_collection;
            $doctor_id = $row['doctor_id'];

    $dia_patients = "SELECT COUNT(DISTINCT tokan_no), category_id, SUM(sale_price) FROM `item_by_doctor` WHERE `category_id` = '2' AND branch_id = '$br_id' AND created >= '$date $start_from' AND created <= '$date $end_at' AND doctor_id = '$doctor_id' "; 
    $run_dia_patients = mysqli_query($con, $dia_patients);
    if(mysqli_num_rows($run_dia_patients) > 0)
    {
        while($row_dia_patients = mysqli_fetch_array($run_dia_patients))
        {
            $count_dia_patients = $row_dia_patients['0'];
            $count_dia_patient_cash = $row_dia_patients['2'];
            $total_lab_test_cash = $total_lab_test_cash + $count_dia_patient_cash;
        }
    }
    else
    {
        $count_dia_patients = 0;
    }
    $total_dia_patients = $total_dia_patients + $count_dia_patients;
        $select_data = "SELECT
    COUNT( CASE WHEN item_by_doctor.category_id = 2 THEN 1 END)tests,
    COUNT( CASE WHEN item_by_doctor.category_id = 3 THEN 1 END)procedures,
    COUNT( CASE WHEN item_by_doctor.category_id = 29 THEN 1 END)consultants,
    COUNT( CASE WHEN item_by_doctor.category_id = 31 THEN 1 END)dentals,
    COUNT( CASE WHEN item_by_doctor.category_id = 32 THEN 1 END)skins,
    COUNT( CASE WHEN item_by_doctor.category_id = 33 THEN 1 END)eyes,
    COUNT( CASE WHEN item_by_doctor.category_id = 34 THEN 1 END)physiotherapies,
    COUNT( CASE WHEN item_by_doctor.category_id = 36 THEN 1 END)minir_procedures,
    COUNT( CASE WHEN item_by_doctor.category_id = 37 THEN 1 END)svds,
    COUNT( CASE WHEN item_by_doctor.category_id = 38 THEN 1 END)dncs,
    COUNT( CASE WHEN item_by_doctor.category_id = 39 THEN 1 END)usgs,
    COUNT( CASE WHEN item_by_doctor.category_id = 40 THEN 1 END)admissions,
    COUNT( CASE WHEN item_by_doctor.category_id = 41 THEN 1 END)gyneas,
    COUNT( CASE WHEN item_by_doctor.category_id = 42 THEN 1 END)emergency,
    COUNT( CASE WHEN item_by_doctor.category_id = 44 THEN 1 END)ecgs
FROM `item_by_doctor` WHERE item_by_doctor.created >= '$date $start_from' AND item_by_doctor.created <= '$date $end_at' AND item_by_doctor.doctor_id = '$doctor_id' AND item_by_doctor.branch_id = '$br_id' AND item_by_doctor.category_id IN(2, 3, 29, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 44); ";
        $run_data = mysqli_query($con, $select_data);
        if(mysqli_num_rows($run_data) > 0)
        {
            while($row_data = mysqli_fetch_array($run_data))
            {
                $tests = $row_data['tests'];
                $total_tests = $total_tests + $tests;
                
                $procedures = $row_data['procedures'];
                $total_procedures = $total_procedures + $procedures;
                
                $consultants = $row_data['consultants'];
                $total_consultants = $total_consultants + $consultants;
                
                $dentals = $row_data['dentals'];
                $total_dentals = $total_dentals + $dentals;
                
                $skins = $row_data['skins'];
                $total_skins = $total_skins + $skins;
                
                $eyes = $row_data['eyes'];
                $total_eyes = $total_eyes + $eyes;
                
                $physiotherapies = $row_data['physiotherapies'];
                $total_physiotherapies = $total_physiotherapies + $physiotherapies;
                
                $minir_procedures = $row_data['minir_procedures'];
                $total_minir_procedures = $total_minir_procedures + $minir_procedures;
                
                $svds = $row_data['svds'];
                $total_svds = $total_svds + $svds;
                
                $dncs = $row_data['dncs'];
                $total_dncs = $total_dncs + $dncs;
                
                $usgs = $row_data['usgs'];
                $total_usgs = $total_usgs + $usgs;
                
                $admissions = $row_data['admissions'];
                $total_admissions = $total_admissions + $admissions;
                
                $gyneas = $row_data['gyneas'];
                $total_gyneas = $total_gyneas + $gyneas;
                
                $emergency = $row_data['emergency'];
                $total_emergency = $total_emergency + $emergency;
                
                $ecgs = $row_data['ecgs'];
                $total_ecgs = $total_ecgs + $ecgs;
                
            }
        }

        $gynae_system = mysqli_num_rows(mysqli_query($con, "SELECT * FROM `gynae_register` WHERE doctor_id = '$doctor_id' AND created >= '$date $start_from' AND created <= '$date $end_at'  AND branch_id = '$br_id'"));
        $total_gynae_system = $total_gynae_system + $gynae_system;
        
        $refered_from_query = "SELECT * FROM `referral_patients` WHERE `from_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND referral_patient_created >= '$date $start_from' AND referral_patient_created <= '$date $end_at' AND branch_id = '$br_id' ";
        $refered = mysqli_num_rows(mysqli_query($con, $refered_from_query));
        $total_refered = $total_refered + $refered;
        
        $refered_to_query = "SELECT * FROM `referral_patients` WHERE `to_user_id` = '$doctor_id' AND `referral_patient_status` > '1' AND referral_patient_created >= '$date $start_from' AND referral_patient_created <= '$date $end_at' ";
        $refered_to = mysqli_num_rows(mysqli_query($con, $refered_to_query));
        $total_refered_to = $total_refered_to + $refered_to;

            $s++; ?>
        <tr>
            <td><?php echo $s; ?></td>
            <td><?php echo $row['doctor_id']; ?></td>
            <td><?php echo $row['tag_name']; ?></td>
            <td><?php echo $row['u_name']; ?></td>
            <td><?php echo $opd; ?></td>
            <td><?php echo $count_dia_patients; ?></td>
            <td><?php echo $tests; ?></td>
            <td>
                <?php 
                if($opd > 0 && $count_dia_patients > 0)
                {   
                    if($opd >= $count_dia_patients)
                    {
                        echo intval(($count_dia_patients/$opd)*100);
                    }
                    else
                    {
                        echo '100';
                    }
                } 
                else 
                { 
                    echo '0';
                }
                ?>
            </td>
            <td><?php echo number_format($count_dia_patient_cash); ?></td>
            <td><?php echo $usgs; ?></td>
            <td><?php echo $svds; ?></td>
            <td><?php echo $dncs; ?></td>
            <td><?php echo $procedures; ?></td>
            <td><?php echo $consultants; ?></td>
            <td><?php echo $skins; ?></td>
            <td><?php echo $eyes; ?></td>
            <td><?php echo $admissions; ?></td>
            <td><?php echo $emergency; ?></td>
            <td><?php echo $ecgs; ?></td>
            <td><?php echo $gyneas; ?></td>
            <td><?php echo $gynae_system; ?></td>
            <td><?php echo $refered; ?></td>
            <td><?php echo $refered_to; ?></td>            
            <td style = "text-align: right;"><?php echo number_format($cash_collection); ?></td>
        </tr>
        <?php 
        $tests = 0;
        $cash_collection = 0;
        $procedures = 0;
        $consultants = 0;
        $dentals = 0;
        $skins = 0;
        $eyes = 0;
        $physiotherapies = 0;
        $minir_procedures = 0;
        $svds = 0;
        $dncs = 0;
        $usgs = 0;
        $admissions = 0;
        $gyneas = 0;
        $emergency = 0;
        $ecgs = 0;
        $gynaes = 0;
        $gynae_system = 0;
        $refered = 0;
        $refered_to = 0;
        }
    }
    ?>
        <tr style = "text-align: right;">
            <td><?php echo $count_run; ?></td>
            <td></td>
            <td></td>
            <td></td>
            <th><?php echo $total_opd; ?></th>
            <?php
            echo '<th>'.$total_dia_patients.'</th>';
            echo '<th>'.$total_tests.'</th>';
            echo '<th></th>';
            echo '<th>'.number_format($total_lab_test_cash).'</th>';
            echo '<th>'.$total_usgs.'</th>
            <th>'.$total_svds.'</th></th>
            <th>'.$total_dncs.'</th>';
            echo '<th>'.$total_procedures.'</th>
            <th>'.$total_consultants.'</th>
            <th>'.$total_skins.'</th>
            <th>'.$total_eyes.'</th>
            <th>'.$total_admissions.'</th>
            <th>'.$total_emergency.'</th>
            <th>'.$total_ecgs.'</th>
            <th>'.$total_gyneas.'</th>';
            ?>
            <th><?php echo $total_gynae_system; ?></th>
            <th><?php echo $total_refered; ?></th>
            <th><?php echo $total_refered_to; ?></th>
            <th><?php echo number_format($total_cash); ?></th>
        </tr>
    </tbody>
</table>
</body>
</html>
<?php mysqli_close($con); ?>