<?php
include 'includes/connect.php';
require_once __DIR__ . '/includes/progress_report_params.php';

$req = progress_report_resolve_request($con);
$date = $req['date'];
$br_id = $req['br_id'];
$like = $req['like'];

$lab_stats = progress_lab_stats_by_doctor($con, $br_id, $like);
$user_names = array();
if (count($lab_stats) > 0) {
    $ids = implode(',', array_keys($lab_stats));
    $run_names = mysqli_query($con, "SELECT id, u_name FROM users WHERE id IN ($ids)");
    if ($run_names) {
        while ($row = mysqli_fetch_assoc($run_names)) {
            $user_names[(int) $row['id']] = $row['u_name'];
        }
    }
}
ksort($lab_stats);
?>
<html>
<head>
    <title><?php echo get_branch_name_by($br_id); ?> <?php echo date_format(date_create($date), ' d F Y'); ?> LAB PROGRESS REPORT</title>
</head>
<body>

<table border="solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS DATE <?php echo date_format(date_create($date), ' d F Y'); ?></h3>
    <h5 align="center">GENERATED BY: <i><?php echo htmlspecialchars($bk_name, ENT_QUOTES, 'UTF-8'); ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>PATIENT NAME</th>
            <th>TOTAL PATIENTs</th>
            <th>TOTAL LAB AMOUNT</th>
        </tr>
    </thead>
<?php
$s = 0;
$total_lab = 0;
$total_count_lab = 0;

if (count($lab_stats) > 0) {
    echo '<tbody>';
    foreach ($lab_stats as $doctor => $stat) {
        $s++;
        $doctor_name = $user_names[$doctor] ?? get_uname_by_id($doctor);
        $count_lab = $stat['count'];
        $labs = $stat['cash'];
        $total_count_lab += $count_lab;
        $total_lab += $labs;
        echo '<tr style="text-align: right;">';
        echo '<td>' . $s . '</td>';
        echo '<td style="text-align: left;">' . htmlspecialchars($doctor_name, ENT_QUOTES, 'UTF-8') . ' (' . (int) $doctor . ')</td>';
        echo '<td>' . $count_lab . '</td>';
        echo '<td>' . $labs . '</td>';
        echo '</tr>';
    }
    echo '</tbody>';
    echo '<tfoot><tr style="text-align: right;"><th></th><th></th><th>' . $total_count_lab . '</th><th>' . $total_lab . '</th></tr></tfoot>';
}
?>
</table>
</body>
</html>
<?php mysqli_close($con); ?>
