<?php
// OPTIMIZED: replaced per-row queries with pre-aggregated batch queries
include 'includes/connect.php';
require_once __DIR__ . '/includes/progress_report_params.php';

if (isset($_GET['date'])) {
    $date = $_GET['date'];
    $br_id = $_GET['br_id'];
} elseif (isset($_POST['date'])) {
    $date = $_POST['date'];
    $br_id = $_POST['br_id'];
} else {
    exit(0);
}

$br_id = (int) $br_id;
$date_esc = mysqli_real_escape_string($con, $date);
$month_prefix = $date_esc . '%';
$tok_date_clause = progress_sql_date_clause($con, $month_prefix);

$stats = array();
$aggregate_sql = "SELECT user_id, tokan_type_id, COUNT(*) AS token_count, COALESCE(SUM(cash), 0) AS cash_total
    FROM tokans
    WHERE branch_id = '$br_id'
    AND $tok_date_clause
    AND tokan_type_id IN ('1', '2', '3', '4')
    AND status = '1'
    GROUP BY user_id, tokan_type_id";
$run_aggregate = mysqli_query($con, $aggregate_sql);
if ($run_aggregate) {
    while ($row = mysqli_fetch_assoc($run_aggregate)) {
        $uid = (int) $row['user_id'];
        $type_id = (string) $row['tokan_type_id'];
        if (!isset($stats[$uid])) {
            $stats[$uid] = array(
                '1' => array('count' => 0, 'cash' => 0),
                '2' => array('count' => 0, 'cash' => 0),
                '3' => array('count' => 0, 'cash' => 0),
                '4' => array('count' => 0, 'cash' => 0),
            );
        }
        $stats[$uid][$type_id] = array(
            'count' => (int) $row['token_count'],
            'cash' => (float) $row['cash_total'],
        );
    }
}

$user_names = array();
if (count($stats) > 0) {
    $user_ids = implode(',', array_keys($stats));
    $name_sql = "SELECT id, u_name FROM users WHERE id IN ($user_ids)";
    $run_names = mysqli_query($con, $name_sql);
    if ($run_names) {
        while ($row = mysqli_fetch_assoc($run_names)) {
            $user_names[(int) $row['id']] = $row['u_name'];
        }
    }
}

ksort($stats);
?>
<html>
<head>
    <title>PRINT RECEPTION PROGRESS REPORT <?php echo get_branch_tag_by($br_id); echo date_format(date_create($date), ' F Y'); ?></title>
</head>
<body>

<table border="solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>RECEPTION PROGRESS <?php echo date_format(date_create($date), ' F Y'); ?></h3>
    <h5 align="center">PROGRESS REPORT IS GENERATED BY: <i><?php echo htmlspecialchars($bk_name, ENT_QUOTES, 'UTF-8'); ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th>
            <th>ID</th>
            <th>NAME</th>
            <th>POOR</th>
            <th>GENERAL</th>
            <th>PRIVATE</th>
            <th>EMERGENCY</th>
            <th>TOTAL COLLECTION</th>
            <th>INCENTIVE</th>
        </tr>
    </thead>
<?php
$s = 0;
$total_poor = 0;
$total_member = 0;
$total_general = 0;
$total_emergency = 0;
$total_incentive = 0;

if (count($stats) > 0) {
    echo '<tbody>';
    foreach ($stats as $doctor => $types) {
        $s++;
        $doctor_name = $user_names[$doctor] ?? get_uname_by_id($doctor);
        $count_poor = $types['1']['count'];
        $poor = $types['1']['cash'];
        $count_member = $types['2']['count'];
        $member = $types['2']['cash'];
        $count_general = $types['3']['count'];
        $general = $types['3']['cash'];
        $count_emergency = $types['4']['count'];
        $emergency = $types['4']['cash'];

        $total_poor += $poor;
        $total_member += $member;
        $total_general += $general;
        $total_emergency += $emergency;

        $incentive = ($count_poor * 1) + ($count_member * 5) + ($count_general * 3);
        $total_incentive += $incentive;
        $row_total = $poor + $member + $general + $emergency;

        echo '<tr style="text-align: right;">';
        echo '<td>' . $s . '</td>';
        echo '<td>' . (int) $doctor . '</td>';
        echo '<td style="text-align: left;">' . htmlspecialchars($doctor_name, ENT_QUOTES, 'UTF-8') . '</td>';
        echo '<td>' . $count_poor . ' -> ' . $poor . '</td>';
        echo '<td>' . $count_general . ' -> ' . $general . '</td>';
        echo '<td>' . $count_member . ' -> ' . $member . '</td>';
        echo '<td>' . $count_emergency . ' -> ' . $emergency . '</td>';
        echo '<td>' . $row_total . '</td>';
        echo '<td>' . $incentive . '</td>';
        echo '</tr>';
    }
    echo '</tbody>';
    echo '<tfoot>
            <tr style="text-align: right;">
                <th colspan="3"></th>';
    echo '<th>' . $total_poor . '</th>';
    echo '<th>' . $total_general . '</th>';
    echo '<th>' . $total_member . '</th>';
    echo '<th>' . $total_emergency . '</th>';
    echo '<th>' . ($total_poor + $total_member + $total_general + $total_emergency) . '</th>';
    echo '<th>' . $total_incentive . '</th>';
    echo '</tr>
        </tfoot>';
}
?>
</table>
<small>
    <span style="color: red;">INCENTIVE:</span> 1 rupee per Poor token, 3 Rupees per General Token &amp; 5 Rupees per Private Token
</small>
</body>
</html>
<?php mysqli_close($con); ?>
