<?php
// OPTIMIZED: replaced per-row queries with pre-aggregated batch queries
include 'includes/connect.php';
require_once __DIR__ . '/includes/progress_report_params.php';

$req = progress_report_resolve_request($con);
$date = $req['date'];
$br_id = $req['br_id'];
$like = $req['like'];

$opds = progress_opd_count_by_doctor($con, $br_id, $like);
$collections = progress_cash_sum_by_doctor($con, $br_id, $like);
$category_stats = progress_category_stats_by_doctor($con, $br_id, $like);
$gynae_system_map = progress_gynae_register_count_by_doctor($con, $br_id, $like);
$refer_from = progress_referral_from_count_by_doctor($con, $like);
$refer_to = progress_referral_to_count_by_doctor($con, $like);

$tok_date_clause = progress_sql_date_clause($con, $like);
$doctor_sql = "SELECT DISTINCT doctor_id FROM tokans
    WHERE doctor_id IN (SELECT id FROM users WHERE branch_id = '$br_id')
    AND $tok_date_clause AND branch_id = '$br_id' ORDER BY doctor_id";
$doctor_ids = array();
$run_doctors = mysqli_query($con, $doctor_sql);
if ($run_doctors) {
    while ($row = mysqli_fetch_assoc($run_doctors)) {
        $doctor_ids[] = (int) $row['doctor_id'];
    }
}

$user_names = array();
if (count($doctor_ids) > 0) {
    $ids = implode(',', $doctor_ids);
    $run_names = mysqli_query($con, "SELECT id, u_name FROM users WHERE id IN ($ids)");
    if ($run_names) {
        while ($row = mysqli_fetch_assoc($run_names)) {
            $user_names[(int) $row['id']] = $row['u_name'];
        }
    }
}

function progress_cat_count($stats, $doctor, $category_id)
{
    return isset($stats[$doctor][$category_id]) ? (int) $stats[$doctor][$category_id]['count_token'] : 0;
}

function progress_cat_cash($stats, $doctor, $category_id)
{
    return isset($stats[$doctor][$category_id]) ? (float) $stats[$doctor][$category_id]['total_cash'] : 0;
}
?>
<html>
<head>
    <style>
        @media print { .noprint { visibility: hidden; } }
    </style>
    <title><?php echo date_format(date_create($date), 'd-m-Y') . ' ' . get_branch_tag_by($br_id); ?> PROGRESS REPORT</title>
</head>
<body>
<div><a class="noprint" href="dashboard.php">GOTO DASHBOARD</a></div>
<table border="solid">
<caption>
    <h2><?php echo $company_name; ?></h2>
    <h2><?php echo get_branch_name_by($br_id); ?></h2>
    <h3>PROGRESS DATE <?php echo date_format(date_create($date), ' d F Y'); ?></h3>
    <h5 align="center">PROGRESS REPORT IS GENERATED BY: <i><?php echo htmlspecialchars($bk_name, ENT_QUOTES, 'UTF-8'); ?></i>, AT: <i><?php echo date('H:i:s d-m-Y'); ?></i></h5>
</caption>
    <thead>
        <tr>
            <th>S#</th><th>ID</th><th>NAME</th><th>OPD</th><th>CONS</th><th>LAB</th><th>CASH</th>
            <th>USG</th><th>SVD</th><th>D&amp;C</th><th>OPERATION</th><th>DENTAL</th><th>SKIN</th><th>EYE</th>
            <th>ADMISSION</th><th>EMERGENCY</th><th>ECG</th><th>GYNAE TOKEN</th><th>GYNAE SYSTEM</th>
            <th>REFERREL BY</th><th>REFERREL TO</th><th>COLLECTION</th>
        </tr>
    </thead>
<?php
$s = 0;
$totals = array(
    'opds' => 0, 'cons_opds' => 0, 'labs' => 0, 'lab_cash' => 0, 'usgs' => 0, 'svds' => 0, 'dncs' => 0,
    'procedures' => 0, 'dentals' => 0, 'skins' => 0, 'eyes' => 0, 'admissions' => 0, 'emergency' => 0,
    'ecg' => 0, 'gynaes' => 0, 'gynae_system' => 0, 'refered' => 0, 'refered_to' => 0, 'collections' => 0,
);

if (count($doctor_ids) > 0) {
    echo '<tbody>';
    foreach ($doctor_ids as $doctor) {
        $s++;
        $opd = $opds[$doctor] ?? 0;
        $collection = $collections[$doctor] ?? 0;
        $labs = progress_cat_count($category_stats, $doctor, 2);
        $lab_cash = progress_cat_cash($category_stats, $doctor, 2);
        $procedures = progress_cat_count($category_stats, $doctor, 3);
        $cons_opds = progress_cat_count($category_stats, $doctor, 29);
        $cons_dentals = progress_cat_count($category_stats, $doctor, 31);
        $skins = progress_cat_count($category_stats, $doctor, 32);
        $eyes = progress_cat_count($category_stats, $doctor, 33);
        $svds = progress_cat_count($category_stats, $doctor, 37);
        $dncs = progress_cat_count($category_stats, $doctor, 38);
        $usgs = progress_cat_count($category_stats, $doctor, 39);
        $admissions = progress_cat_count($category_stats, $doctor, 40);
        $gynaes = progress_cat_count($category_stats, $doctor, 41);
        $emergency = progress_cat_count($category_stats, $doctor, 42);
        $ecg = progress_cat_count($category_stats, $doctor, 44);
        $gynae_system = $gynae_system_map[$doctor] ?? 0;
        $refered = $refer_from[$doctor] ?? 0;
        $refered_to = $refer_to[$doctor] ?? 0;

        $totals['opds'] += $opd;
        $totals['cons_opds'] += $cons_opds;
        $totals['labs'] += $labs;
        $totals['lab_cash'] += $lab_cash;
        $totals['usgs'] += $usgs;
        $totals['svds'] += $svds;
        $totals['dncs'] += $dncs;
        $totals['procedures'] += $procedures;
        $totals['dentals'] += $cons_dentals;
        $totals['skins'] += $skins;
        $totals['eyes'] += $eyes;
        $totals['admissions'] += $admissions;
        $totals['emergency'] += $emergency;
        $totals['ecg'] += $ecg;
        $totals['gynaes'] += $gynaes;
        $totals['gynae_system'] += $gynae_system;
        $totals['refered'] += $refered;
        $totals['refered_to'] += $refered_to;
        $totals['collections'] += $collection;

        $doctor_name = $user_names[$doctor] ?? get_uname_by_id($doctor);
        echo '<tr style="text-align: right;">';
        echo '<td>' . $s . '</td><td>' . $doctor . '</td>';
        echo '<td style="text-align: left;">' . htmlspecialchars($doctor_name, ENT_QUOTES, 'UTF-8') . '</td>';
        echo '<td>' . $opd . '</td><td>' . $cons_opds . '</td><td>' . $labs . '</td><td>' . number_format((float)($lab_cash ?? 0)) . '</td>';
        echo '<td>' . $usgs . '</td><td>' . $svds . '</td><td>' . $dncs . '</td><td>' . $procedures . '</td>';
        echo '<td>' . $cons_dentals . '</td><td>' . $skins . '</td><td>' . $eyes . '</td><td>' . $admissions . '</td>';
        echo '<td>' . $emergency . '</td><td>' . $ecg . '</td><td>' . $gynaes . '</td><td>' . $gynae_system . '</td>';
        echo '<td>' . $refered . '</td><td>' . $refered_to . '</td><td>' . number_format((float)($collection ?? 0)) . '</td>';
        echo '</tr>';
    }
    echo '</tbody><tfoot><tr style="text-align: right;"><th colspan="3"></th>';
    echo '<th>' . $totals['opds'] . '</th><th>' . $totals['cons_opds'] . '</th><th>' . $totals['labs'] . '</th>';
    echo '<th>' . number_format((float)($totals['lab_cash'] ?? 0)) . '</th><th>' . $totals['usgs'] . '</th><th>' . $totals['svds'] . '</th>';
    echo '<th>' . $totals['dncs'] . '</th><th>' . $totals['procedures'] . '</th><th>' . $totals['dentals'] . '</th>';
    echo '<th>' . $totals['skins'] . '</th><th>' . $totals['eyes'] . '</th><th>' . $totals['admissions'] . '</th>';
    echo '<th>' . $totals['emergency'] . '</th><th>' . $totals['ecg'] . '</th><th>' . $totals['gynaes'] . '</th>';
    echo '<th>' . $totals['gynae_system'] . '</th><th>' . $totals['refered'] . '</th><th>' . $totals['refered_to'] . '</th>';
    echo '<th>' . number_format((float)($totals['collections'] ?? 0)) . '</th></tr></tfoot>';
}
?>
</table>
</body>
</html>
<?php mysqli_close($con); ?>
